"""
Django settings for koin project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=)w(dd$t=llhre6=33#s%ba&f4lqulq^g6ff=e8hb#i7+n&e&^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'finances',
    'simulation',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'koin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'finances.context_processors.datos_globales_koin',
            ],
        },
    },
]

WSGI_APPLICATION = 'koin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# --- CONFIGURACIÓN DE AUTENTICACIÓN PARA KOIN ---

# 1. Si alguien sin registrar intenta entrar a una zona protegida, envíalo aquí:
LOGIN_URL = 'registro' # Usamos el 'name' de la url en lugar de la ruta escrita

# 2. Cuando alguien haga login con éxito, envíalo al Dashboard:
LOGIN_REDIRECT_URL = 'dashboard' 

# 3. Cuando alguien cierre sesión, devuélvelo al login:
LOGOUT_REDIRECT_URL = 'login'

# Busca la sección de AUTH_USER_MODEL o agrégala al final del archivo
AUTH_USER_MODEL = 'finances.Usuario'

# Como ahora usamos correo_usuario como USERNAME_FIELD, 
# el backend personalizado que hicimos antes ya no es estrictamente necesario,
# pero asegúrate de que tus backends de autenticación estén limpios:
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

BASE_DIR = Path(__file__).resolve().parent.parent

# --- CONFIGURACIÓN DE ARCHIVOS ESTÁTICOS ---

# La URL que el navegador usará (ej. 127.0.0.1:8000/static/img/logo.png)
STATIC_URL = 'static/'

# Le decimos a Django en qué carpetas físicas de tu computadora debe buscar
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# ==========================================
# CONFIGURACIÓN DE PWA (Koin)
# ==========================================
PWA_APP_NAME = 'Koin'
PWA_APP_DESCRIPTION = "Gestión financiera para el núcleo familiar."
PWA_APP_THEME_COLOR = '#062F35' # Tu color deep-teal
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone' # Esto oculta la barra del navegador (parecerá app nativa)
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait' # Bloquea la app en modo vertical
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = '#062F35'
PWA_APP_ICONS = [
    {
        'src': '/static/images/icon-512.png', # Usa el icono que ya tienes
        'sizes': '512x512',
        'type': 'image/png'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/icon-512.png',
        'sizes': '512x512',
        'type': 'image/png'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es-ve'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'mi_serviceworker.js')