# Generated by Django 6.0.5 on 2026-06-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_movimiento_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='tasa_cambio',
        ),
    ]
