# Generated by Django 6.0.5 on 2026-06-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_codigorecuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pregunta_seguridad',
            field=models.CharField(choices=[('mascota', '¿Cuál fue el nombre de tu primera mascota?'), ('ciudad', '¿En qué ciudad nació tu madre?'), ('apodo', '¿Cuál era tu apodo en la infancia?')], default='mascota', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='respuesta_seguridad',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='CodigoRecuperacion',
        ),
    ]
